### ISSUE TITLE
Alternative text should appear in headings

### ISSUE THREAD

**Issue by hteumeuleu** [MaartenWL/accessible-email.org#1]
When using an image within a heading, it would be great if text could appear next to the tag name. Currently, nothing is showed.

![Screenshot with empty heading](https://cloud.githubusercontent.com/assets/3451753/14024531/d7504980-f1e9-11e5-95a3-2c6cafb5eecd.png)

Here is the code used.

``` html
 <!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>Test</title>
</head>
<body>
    <h1><img src="foobar.jpg" alt="Title in an image" /></h1>
    <h2>Lorem ipsum dolor sit amet.</h2>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi necessitatibus enim earum fuga, numquam quam! Cumque molestias, amet, rem labore sit, aliquam eaque vitae, temporibus fuga eligendi ratione consequuntur nemo?
    </p>
</body>
</html>
```

**Comment by MaartenWL** [comment]
Thanx for your input! I've fixed this issue. After some testing I will update the site probably next week.
